# SPDX-License-Identifier: GPL-3.0-or-later
# Copyright (C) 2024-2026 SYMFLUENCE Team <dev@symfluence.org>

"""Base classes for model preprocessors, runners, postprocessors, config adapters, and result extractors."""
from __future__ import annotations

from symfluence.core.exceptions import ConfigValidationError

from .base_config import AutoGeneratedConfigAdapter, ModelConfigAdapter, create_config_adapter
from .base_extractor import ModelResultExtractor
from .base_postprocessor import BaseModelPostProcessor
from .base_preprocessor import BaseModelPreProcessor
from .base_runner import BaseModelRunner
from .protocols import ModelPostProcessor, ModelPreProcessor, ModelRunner
from .standard_postprocessor import RoutedModelPostProcessor, StandardModelPostProcessor

__all__ = [
    'BaseModelPreProcessor',
    'BaseModelRunner',
    'BaseModelPostProcessor',
    'StandardModelPostProcessor',
    'RoutedModelPostProcessor',
    'ModelConfigAdapter',
    'AutoGeneratedConfigAdapter',
    'ConfigValidationError',
    'create_config_adapter',
    'ModelResultExtractor',
    'ModelRunner',
    'ModelPreProcessor',
    'ModelPostProcessor',
]
