# SPDX-License-Identifier: GPL-3.0-or-later
# Copyright (C) 2024-2026 SYMFLUENCE Team <dev@symfluence.org>

"""Base classes for model preprocessors, runners, postprocessors, config adapters, and result extractors."""
from __future__ import annotations

from typing import TYPE_CHECKING

from symfluence.core.exceptions import ConfigValidationError

# Lazy re-exports (PEP 562). Model config adapters import this package at
# plugin-discovery time (i.e. at `import symfluence`); an eager import of the
# postprocessor/runner bases would drag the geospatial and observation stacks
# into every CLI startup.
_LAZY_IMPORTS = {
    'AutoGeneratedConfigAdapter': ('.base_config', 'AutoGeneratedConfigAdapter'),
    'ModelConfigAdapter': ('.base_config', 'ModelConfigAdapter'),
    'create_config_adapter': ('.base_config', 'create_config_adapter'),
    'ModelResultExtractor': ('.base_extractor', 'ModelResultExtractor'),
    'BaseModelPostProcessor': ('.base_postprocessor', 'BaseModelPostProcessor'),
    'BaseModelPreProcessor': ('.base_preprocessor', 'BaseModelPreProcessor'),
    'BaseModelRunner': ('.base_runner', 'BaseModelRunner'),
    'ModelPostProcessor': ('.protocols', 'ModelPostProcessor'),
    'ModelPreProcessor': ('.protocols', 'ModelPreProcessor'),
    'ModelRunner': ('.protocols', 'ModelRunner'),
    'RoutedModelPostProcessor': ('.standard_postprocessor', 'RoutedModelPostProcessor'),
    'StandardModelPostProcessor': ('.standard_postprocessor', 'StandardModelPostProcessor'),
}


def __getattr__(name: str):
    """Lazy import handler for base-class re-exports."""
    if name in _LAZY_IMPORTS:
        module_path, attr_name = _LAZY_IMPORTS[name]
        from importlib import import_module
        value = getattr(import_module(module_path, package=__name__), attr_name)
        globals()[name] = value
        return value
    raise AttributeError(f"module {__name__!r} has no attribute {name!r}")


def __dir__():
    return sorted(list(_LAZY_IMPORTS.keys()) + ['ConfigValidationError'])


if TYPE_CHECKING:
    from .base_config import (
        AutoGeneratedConfigAdapter,
        ModelConfigAdapter,
        create_config_adapter,
    )
    from .base_extractor import ModelResultExtractor
    from .base_postprocessor import BaseModelPostProcessor
    from .base_preprocessor import BaseModelPreProcessor
    from .base_runner import BaseModelRunner
    from .protocols import ModelPostProcessor, ModelPreProcessor, ModelRunner
    from .standard_postprocessor import RoutedModelPostProcessor, StandardModelPostProcessor

__all__ = [
    'BaseModelPreProcessor',
    'BaseModelRunner',
    'BaseModelPostProcessor',
    'StandardModelPostProcessor',
    'RoutedModelPostProcessor',
    'ModelConfigAdapter',
    'AutoGeneratedConfigAdapter',
    'ConfigValidationError',
    'create_config_adapter',
    'ModelResultExtractor',
    'ModelRunner',
    'ModelPreProcessor',
    'ModelPostProcessor',
]
